api_login_check:
    path: /api/v1/auth/login

api_refresh_token:
    path: /api/v1/auth/refresh
    
app.swagger_ui:
    path: /api/doc/{area}
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
