name: Workflow for Publisher API
on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: php:8.2
    services:
      test-database:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: \!ChangeMe\!
          POSTGRES_DB: app_test
          POSTGRES_USER: app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install package manager(composer)
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - name: Install container dependencies
        run: apt-get update && apt-get -y install git zip unzip
      - name: Install project dependencies
        run: composer install --prefer-dist && composer dump-autoload
      - name: Run tests and collect coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
