name: Workflow for Publisher API
on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: composer:2.6.5
    services:
      test-database:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: \!ChangeMe\!
          POSTGRES_DB: app_test
          POSTGRES_USER: app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer self-update && composer update && composer dump-autoload
      - name: Run tests and collect coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
